# Generated by Django 2.1.8 on 2019-12-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('novel_idx', models.IntegerField(primary_key=True, serialize=False)),
                ('novel_title', models.CharField(max_length=20)),
                ('novel_cont', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Novels',
            fields=[
                ('novel_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('novel_name', models.CharField(max_length=20)),
                ('novel_author', models.CharField(max_length=20)),
                ('novel_pv', models.IntegerField(default=0)),
                ('novel_img', models.CharField(max_length=20)),
                ('novel_type', models.CharField(max_length=20)),
                ('novel_des', models.CharField(max_length=100)),
                ('novel_addTime', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novels'),
        ),
    ]
