# Generated by Django 2.1.8 on 2019-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chart',
            name='novel_idx',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='novel_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='novels',
            name='novel_addTime',
            field=models.DateTimeField(auto_now=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='novels',
            name='novel_img',
            field=models.CharField(max_length=100),
        ),
    ]
