# Generated by Django 2.1.8 on 2019-12-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20191215_1821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('novel', 'novel_idx')},
        ),
    ]
